default_language_version:
  python: python3

repos:
  # Use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy-ndsl
        args: ["--config-file", "pyproject.toml"]
        additional_dependencies: [types-PyYAML]
        files: ndsl
        exclude: |
          (?x)^(
          ndsl/ndsl/gt4py_utils.py |
          )$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8
        language_version: python3
        additional_dependencies: [Flake8-pyproject, flake8-bugbear]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --indent, "2"]
      - id: pretty-format-yaml
        args: [--autofix, --preserve-quotes, --indent, "2", --offset, "2"]

  - repo: https://github.com/georgek/tach-pre-commit
    rev: v0.32.2
    hooks:
      - id: tach
