name: "pace unit tests"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  pace_unit_tests:
    uses: NOAA-GFDL/pace/.github/workflows/main_unit_tests.yaml@develop
    with:
      ndsl_trigger:  true
