name: "SHiELD Translate tests"
on:
  pull_request:

jobs:
  shield_translate_tests:
    uses: NOAA-GFDL/pySHiELD/.github/workflows/translate.yaml@develop
    with:
      component_trigger: true
      component_name: NDSL
